In [66]:
import pandas as pd

df = pd.read_csv(r'D:\github\Customer_shopping_behaviour_analysis\data\customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [68]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [69]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [70]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [71]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [72]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [73]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [74]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [75]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [76]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [77]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [78]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [79]:
df = df.drop('promo_code_used', axis=1)

In [80]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [81]:
df.to_csv(
    r'D:\github\Customer_shopping_behaviour_analysis\data\customer_shopping_behavior_cleaned.csv',
    index=False
)

print("Cleaned dataset saved!")

Cleaned dataset saved!

In [82]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   str
 16  frequency_of_purchases   3900 non-null   str
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), str(12)
memory usage: 552.6 KB

In [84]:
df.shape

(3900, 19)

In [85]:
df['category'].value_counts()

category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

In [86]:
df.groupby('gender')['purchase_amount'].mean()

gender
Female    60.249199
Male      59.536199
Name: purchase_amount, dtype: float64

In [87]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "mysqljaanu56"
host = "localhost"
port = "3306"
database = "customer_behavior"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [88]:
!pip install ipython-sql sqlalchemy

Requirement already satisfied: ipython-sql in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (0.5.0)
Requirement already satisfied: sqlalchemy in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (2.0.50)
Requirement already satisfied: prettytable in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython-sql) (9.14.1)
Requirement already satisfied: sqlparse in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: colorama>=0.4.4 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: psutil>=7 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from ipython->ipython-sql) (5.15.1)
Requirement already satisfied: wcwidth in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from jedi>=0.18.2->ipython->ipython-sql) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.1)
Requirement already satisfied: pure-eval in D:\github\Customer_shopping_behaviour_analysis\venv\Lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)

In [89]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [90]:
%sql sqlite:///customer.db

In [91]:
import pandas as pd

df = pd.read_csv("customer_data.csv")  # change file name if different
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'customer_data.csv'

In [ ]:
df = pd.read_csv(r'D:\github\Customer_shopping_behaviour_analysis\data\customer_shopping_behavior.csv')

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///customer.db")

df.to_sql("customer", engine, if_exists="replace", index=False)

3900

In [ ]:
%sql sqlite:///customer.db

In [ ]:
%%sql
SELECT * FROM customer LIMIT 5;

 * sqlite:///customer.db
Done.

KeyError: 'DEFAULT'

In [ ]:
%config SqlMagic.style = 'PLAIN_COLUMNS'

In [ ]:
%%sql
SELECT * FROM customer LIMIT 5;

 * sqlite:///customer.db
Done.

KeyError: 'PLAIN_COLUMNS'

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("customer.db")

pd.read_sql_query("SELECT * FROM customer LIMIT 5", conn)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
pd.read_sql_query("""
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender
""", conn)

DatabaseError: Execution failed on sql '
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender
': no such column: purchase_amount

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("customer.db")

pd.read_sql_query("SELECT * FROM customer LIMIT 5", conn)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)

       name
0  customer

In [ ]:
pd.read_sql_query("SELECT * FROM customer LIMIT 5;", conn)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
pd.read_sql_query("""
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender
""", conn)

DatabaseError: Execution failed on sql '
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender
': no such column: purchase_amount

In [ ]:
pd.read_sql_query("PRAGMA table_info(customer);", conn)

    cid                    name    type  notnull dflt_value  pk
0     0             Customer ID  BIGINT        0       None   0
1     1                     Age  BIGINT        0       None   0
2     2                  Gender    TEXT        0       None   0
3     3          Item Purchased    TEXT        0       None   0
4     4                Category    TEXT        0       None   0
5     5   Purchase Amount (USD)  BIGINT        0       None   0
6     6                Location    TEXT        0       None   0
7     7                    Size    TEXT        0       None   0
8     8                   Color    TEXT        0       None   0
9     9                  Season    TEXT        0       None   0
10   10           Review Rating   FLOAT        0       None   0
11   11     Subscription Status    TEXT        0       None   0
12   12           Shipping Type    TEXT        0       None   0
13   13        Discount Applied    TEXT        0       None   0
14   14         Promo Code Used    TEXT        0       None   0
15   15      Previous Purchases  BIGINT        0       None   0
16   16          Payment Method    TEXT        0       None   0
17   17  Frequency of Purchases    TEXT        0       None   0

In [ ]:
pd.read_sql_query("""
SELECT Gender,
       SUM([Purchase Amount (USD)]) AS revenue
FROM customer
GROUP BY Gender
""", conn)

   Gender  revenue
0  Female    75191
1    Male   157890

In [ ]:
pd.read_sql_query("""
SELECT Customer ID, [Purchase Amount (USD)]
FROM customer
WHERE [Discount Applied] = 'Yes'
  AND [Purchase Amount (USD)] >= (
      SELECT AVG([Purchase Amount (USD)]) FROM customer
  )
""", conn)

DatabaseError: Execution failed on sql '
SELECT Customer ID, [Purchase Amount (USD)]
FROM customer
WHERE [Discount Applied] = 'Yes'
  AND [Purchase Amount (USD)] >= (
      SELECT AVG([Purchase Amount (USD)]) FROM customer
  )
': no such column: Customer

In [ ]:
pd.read_sql_query("""
SELECT [Customer ID], [Purchase Amount (USD)]
FROM customer
WHERE [Discount Applied] = 'Yes'
  AND [Purchase Amount (USD)] >= (
      SELECT AVG([Purchase Amount (USD)]) FROM customer
  )
""", conn)

     Customer ID  Purchase Amount (USD)
0              2                     64
1              3                     73
2              4                     90
3              7                     85
4              9                     97
..           ...                    ...
834         1667                     64
835         1671                     73
836         1673                     73
837         1674                     62
838         1676                     90

[839 rows x 2 columns]

In [ ]:
pd.read_sql_query("""
SELECT [Item Purchased],
       ROUND(AVG([Review Rating]),2) AS avg_rating
FROM customer
GROUP BY [Item Purchased]
ORDER BY avg_rating DESC
LIMIT 5
""", conn)

  Item Purchased  avg_rating
0         Gloves        3.86
1        Sandals        3.84
2          Boots        3.82
3            Hat        3.80
4          Skirt        3.79

In [ ]:
pd.read_sql_query("""
SELECT [Shipping Type],
       ROUND(AVG([Purchase Amount (USD)]),2) AS avg_spend
FROM customer
GROUP BY [Shipping Type]
""", conn)

    Shipping Type  avg_spend
0  2-Day Shipping      60.73
1         Express      60.48
2   Free Shipping      60.41
3    Next Day Air      58.63
4        Standard      58.46
5    Store Pickup      59.89

In [ ]:
pd.read_sql_query("""
SELECT [Subscription Status],
       COUNT([Customer ID]) AS total_customers,
       ROUND(AVG([Purchase Amount (USD)]),2) AS avg_spend,
       ROUND(SUM([Purchase Amount (USD)]),2) AS total_revenue
FROM customer
GROUP BY [Subscription Status]
""", conn)

  Subscription Status  total_customers  avg_spend  total_revenue
0                  No             2847      59.87       170436.0
1                 Yes             1053      59.49        62645.0

In [ ]:
pd.read_sql_query("""
SELECT [Item Purchased],
       ROUND(100.0 * SUM(CASE WHEN [Discount Applied] = 'Yes' THEN 1 ELSE 0 END)
       / COUNT(*),2) AS discount_rate
FROM customer
GROUP BY [Item Purchased]
ORDER BY discount_rate DESC
LIMIT 5
""", conn)

  Item Purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [ ]:
pd.read_sql_query("""
SELECT 
CASE 
    WHEN [Previous Purchases] = 1 THEN 'New'
    WHEN [Previous Purchases] BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT([Customer ID]) AS total_customers
FROM customer
GROUP BY customer_segment
""", conn)

  customer_segment  total_customers
0            Loyal             3116
1              New               83
2        Returning              701

In [ ]:
pd.read_sql_query("""
SELECT *
FROM (
    SELECT [Category],
           [Item Purchased],
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY [Category]
               ORDER BY COUNT(*) DESC
           ) AS rank
    FROM customer
    GROUP BY [Category], [Item Purchased]
)
WHERE rank <= 3
""", conn)

       Category Item Purchased  total_orders  rank
0   Accessories        Jewelry           171     1
1   Accessories     Sunglasses           161     2
2   Accessories           Belt           161     3
3      Clothing          Pants           171     1
4      Clothing         Blouse           171     2
5      Clothing          Shirt           169     3
6      Footwear        Sandals           160     1
7      Footwear          Shoes           150     2
8      Footwear       Sneakers           145     3
9     Outerwear         Jacket           163     1
10    Outerwear           Coat           161     2

In [ ]:
pd.read_sql_query("""
SELECT [Subscription Status],
       COUNT([Customer ID]) AS repeat_buyers
FROM customer
WHERE [Previous Purchases] > 5
GROUP BY [Subscription Status]
""", conn)

  Subscription Status  repeat_buyers
0                  No           2518
1                 Yes            958

In [ ]:
pd.read_sql_query("""
SELECT Age,
       SUM([Purchase Amount (USD)]) AS revenue
FROM customer
GROUP BY Age
ORDER BY revenue DESC
""", conn)

    Age  revenue
0    49     5552
1    69     5484
2    25     5372
3    54     5282
4    41     5282
5    57     5200
6    28     5104
7    19     4941
8    50     4930
9    31     4864
10   62     4809
11   32     4796
12   53     4752
13   37     4737
14   43     4698
15   51     4601
16   65     4590
17   58     4521
18   63     4519
19   36     4511
20   29     4499
21   27     4460
22   21     4423
23   30     4374
24   42     4357
25   59     4348
26   55     4334
27   46     4318
28   35     4314
29   56     4293
30   24     4291
31   68     4287
32   52     4255
33   26     4212
34   61     4172
35   64     4170
36   38     4169
37   18     4139
38   45     4085
39   66     4065
40   39     4057
41   23     4029
42   40     4026
43   47     4019
44   22     4011
45   33     3960
46   70     3810
47   34     3759
48   60     3730
49   48     3576
50   20     3424
51   44     3312
52   67     3258